# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225)),
                ('address', models.TextField(max_length=225)),
                ('date', models.TextField(max_length=225)),
            ],
        ),
    ]
