# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('-date',), 'verbose_name': 'Feed', 'verbose_name_plural': 'Feed'},
        ),
    ]
